class App{
    //コンストラクター
    constructor(){
        this.eventHandlers=[];
        this.intervals=[];

        //ページのロードが完了したとき、タイトル画面を描画する関数を実行する
        window.addEventListener('load',()=>{
            this.title();
        });
    }
    //「1」を「01」にしてくれる関数
    twoDigit(num){
        return num<10?`0${num}`:num.toString();
    }
    //タイトル
    title(){
        //全てのイベントハンドラーを解除　（この関数の前に実行された関数でリスナーされたイベントのハンドラーはすべて不要なため）
        if(this.eventHandlers.length){
            for(let i=0;i<this.eventHandlers.length;i++)
            {
                if(this.eventHandlers[i])document.removeEventListener(this.eventHandlers[i].typeName,this.eventHandlers[i].callback);
            }
            this.eventHandlers=[];
        }
        //UIを構築し描画
        let titleElement=`<div class="title"><h1>タイピングゲーム</h1><button onclick="app.playTypingGame();">ゲーム開始</button></div>`;
        let containerElement=`<div class=container>${titleElement}</div>`;
        let mainElement=`<main>${containerElement}</main>`;

        document.querySelector('body').innerHTML=mainElement;

        return true;
    }

    //タイピングゲームを準備（Enterキーが押されたらゲームの初期化と開始を行う）
    playTypingGame(){
        //タイピングゲームのデータがない場合、出題データファイルをフェッチして自分をコールバックする
        if(this.typingGame_data){
            this.typingGame_data={
                questionContents:[
                    {
                        "string":"吾輩は猫である",
                        "characters":[
                            {
                                "text":"吾",
                                "hiragana":"わが",
                                "katakana":"ワガ",
                                "romaji":"waga"
                            },
                            {
                                "text":"輩",
                                "hiragana":"はい",
                                "katakana":"ハイ",
                                "romaji":"hai"   
                            },
                            {
                                "text":"は",
                                "hiragana":"は",
                                "katakana":"ハ",
                                "romaji":"ha"   
                            },
                            {
                                "text":"猫",
                                "hiragana":"ねこ",
                                "katakana":"ネコ",
                                "romaji":"neko"   
                            },
                            {
                                "text":"で",
                                "hiragana":"で",
                                "katakana":"で",
                                "romaji":"de"   
                            },
                            {
                                "text":"あ",
                                "hiragana":"あ",
                                "katakana":"あ",
                                "romaji":"a"   
                            },
                            {
                                "text":"る",
                                "hiragana":"る",
                                "katakana":"ル",
                                "romaji":"ru"   
                            }
                        ]
                    },
                    {
                        "string":"雨ニモマケズ風ニモマケズ",
                        "characters":[
                            {
                                "text":"雨",
                                "hiragana":"あめ",
                                "katakana":"アメ",
                                "romaji":"ame"
                            },
                            {
                                "text":"ニ",
                                "hiragana":"に",
                                "katakana":"ニ",
                                "romaji":"ni"   
                            },
                            {
                                "text":"モ",
                                "hiragana":"に",
                                "katakana":"モ",
                                "romaji":"ni"   
                            },
                            {
                                "text":"マ",
                                "hiragana":"ま",
                                "katakana":"マ",
                                "romaji":"ma"   
                            },
                            {
                                "text":"ケ",
                                "hiragana":"け",
                                "katakana":"ケ",
                                "romaji":"ke"   
                            },
                            {
                                "text":"ズ",
                                "hiragana":"ず",
                                "katakana":"ズ",
                                "romaji":"zu"   
                            },
                            {
                                "text":"風",
                                "hiragana":"かぜ",
                                "katakana":"カゼ",
                                "romaji":"kaze"   
                            },
                            {
                                "text":"ニ",
                                "hiragana":"に",
                                "katakana":"ニ",
                                "romaji":"ni"   
                            },
                            {
                                "text":"モ",
                                "hiragana":"に",
                                "katakana":"モ",
                                "romaji":"ni"   
                            },
                            {
                                "text":"マ",
                                "hiragana":"ま",
                                "katakana":"マ",
                                "romaji":"ma"   
                            },
                            {
                                "text":"ケ",
                                "hiragana":"け",
                                "katakana":"ケ",
                                "romaji":"ke"   
                            },
                            {
                                "text":"ズ",
                                "hiragana":"ず",
                                "katakana":"ズ",
                                "romaji":"zu"   
                            },
                        ]
                    },
                    {
                        
                        "string":"こんにちは、世界！",
                        "characters":[
                            {
                                "text":"こ",
                                "hiragana":"こ",
                                "katakana":"コ",
                                "romaji":"ko"
                            },
                            {
                                "text":"ん",
                                "hiragana":"ん",
                                "katakana":"ン",
                                "romaji":"nn"   
                            },
                            {
                                "text":"に",
                                "hiragana":"に",
                                "katakana":"ニ",
                                "romaji":"ni"   
                            },
                            {
                                "text":"ち",
                                "hiragana":"ち",
                                "katakana":"チ",
                                "romaji":"ti"   
                            },
                            {
                                "text":"は",
                                "hiragana":"は",
                                "katakana":"ハ",
                                "romaji":"ha"   
                            },
                            {
                                "text":"、",
                                "hiragana":"、",
                                "katakana":"",
                                "romaji":","   
                            },
                            {
                                "text":"世",
                                "hiragana":"せ",
                                "katakana":"セ",
                                "romaji":"se"   
                            },
                            {
                                "text":"界",
                                "hiragana":"かい",
                                "katakana":"カイ",
                                "romaji":"kai"   
                            },
                            {
                                "text":"！",
                                "hiragana":"！",
                                "katakana":"！",
                                "romaji":"!"   
                            },
                        ]
                    },
                    {
                        
                        "string":"早起きは三文の徳",
                        "characters":[
                            {
                                "text":"早",
                                "hiragana":"はや",
                                "katakana":"ハヤ",
                                "romaji":"haya"
                            },
                            {
                                "text":"起",
                                "hiragana":"お",
                                "katakana":"オ",
                                "romaji":"o"   
                            },
                            {
                                "text":"モ",
                                "hiragana":"に",
                                "katakana":"モ",
                                "romaji":"ni"   
                            },
                            {
                                "text":"マ",
                                "hiragana":"ま",
                                "katakana":"マ",
                                "romaji":"ma"   
                            },
                            {
                                "text":"ケ",
                                "hiragana":"け",
                                "katakana":"ケ",
                                "romaji":"ke"   
                            },
                            {
                                "text":"ズ",
                                "hiragana":"ず",
                                "katakana":"ズ",
                                "romaji":"zu"   
                            },
                            {
                                "text":"風",
                                "hiragana":"かぜ",
                                "katakana":"カゼ",
                                "romaji":"kaze"   
                            },
                            {
                                "text":"ニ",
                                "hiragana":"に",
                                "katakana":"ニ",
                                "romaji":"ni"   
                            },
                            {
                                "text":"モ",
                                "hiragana":"に",
                                "katakana":"モ",
                                "romaji":"ni"   
                            },
                            {
                                "text":"マ",
                                "hiragana":"ま",
                                "katakana":"マ",
                                "romaji":"ma"   
                            },
                            {
                                "text":"ケ",
                                "hiragana":"け",
                                "katakana":"ケ",
                                "romaji":"ke"   
                            },
                            {
                                "text":"ズ",
                                "hiragana":"ず",
                                "katakana":"ズ",
                                "romaji":"zu"   
                            },
                        ]
                    }
                ]
            }
        }
    }
}